In [1]:
import tensorflow as tf
import numpy as np

In [3]:
n_input = 3
n_neurons = 5

### 使用矩阵形式实现RNN网络
实现最简单的RNN网络

In [5]:
x0 = tf.placeholder(tf.float32, [None, n_input])
x1 = tf.placeholder(tf.float32, [None, n_input])

Wx = tf.Variable(tf.truncated_normal([n_input, n_neurons], dtype=tf.float32, stddev=0.1))
Wy = tf.Variable(tf.truncated_normal([n_neurons, n_neurons], dtype=tf.float32, stddev=0.1))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(x0, Wx) + b)

Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(x1, Wx) + b)

x0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]])
x1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    y0_val, y1_val = sess.run([Y0, Y1], feed_dict={x0: x0_batch, x1:x1_batch})
    print(y0_val)
    print(y1_val)
    

[[ 0.1799698   0.00931692  0.07043761 -0.43363261  0.00810006]
 [ 0.47598353 -0.29216325  0.37975335 -0.94376749 -0.25405109]
 [ 0.69294834 -0.54495496  0.62244606 -0.995772   -0.48352724]
 [-0.14528699 -0.2630547   0.50710464 -0.88405937 -0.47964346]]
[[ 0.68839753 -0.74964708  0.71633029 -0.99792862 -0.61965233]
 [ 0.02885482 -0.11963315 -0.11992651  0.14578612  0.16900289]
 [ 0.47637266 -0.65785044  0.36910301 -0.95525455 -0.35340005]
 [ 0.12127631 -0.4350065   0.13012896 -0.64576995 -0.10354767]]


### 使用tensorflow 提供的现有的网络来实现

In [10]:
tf.reset_default_graph()
x0 = tf.placeholder(tf.float32, [None, n_input])
x1 = tf.placeholder(tf.float32, [None, n_input])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
out_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, [x0, x1], dtype=tf.float32)
Y0, Y1 = out_seqs

x0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]])
x1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    y0_val, y1_val = sess.run([Y0, Y1], feed_dict={x0: x0_batch, x1:x1_batch})
    print(y0_val)
    print(y1_val)

[[ 0.2870166   0.74821717  0.75459671  0.14574462  0.88528639]
 [-0.15449914  0.84353352  0.95306528 -0.16276072  0.99990314]
 [-0.54187393  0.9047327   0.99177581 -0.44241726  0.99999994]
 [-0.37033784 -0.99925017 -0.15038314 -0.92454737  0.97204143]]
[[-0.76205266 -0.17201045  0.98986125 -0.78598636  1.        ]
 [ 0.58631444  0.03882574  0.85502857  0.43322185  0.79885793]
 [-0.52539694 -0.37900975  0.97634476 -0.00414488  0.99999803]
 [-0.66244298 -0.63323975 -0.30876365  0.79047835  0.96054465]]
